Практическая работа 1 - Атаманчук А.В. КВБО-01-22

In [1]:
import numpy as np

In [2]:
first_array_from_list = np.array([1, 2, 3, 4])  # одномерный массив
second_array_from_list = np.array([[1, 2, 3], [4, 5, 6]])  # двумерный массив

In [3]:
array_of_zeros = np.zeros((2, 3)) 
array_of_ones = np.ones(5) 
range_array = np.arange(0, 10, 0.5)  # массив от 0 до 10 с шагом 0.5

In [4]:
# Демонстрация shape и dtype
print("Форма массива second_array_from_list:", second_array_from_list.shape)
print("Тип данных массива range_array:", range_array.dtype)

Форма массива second_array_from_list: (2, 3)
Тип данных массива range_array: float64


In [5]:
element = second_array_from_list[1, 2]  # элемент второй строки и третьего столбца
subarray = second_array_from_list[:, 1:]  # подмассив всех строк, начиная со второго столбца

In [6]:
print("Отдельный элемент:", element)
print("Подмассив:\n", subarray)

Отдельный элемент: 6
Подмассив:
 [[2 3]
 [5 6]]


In [7]:
sum_array = first_array_from_list + np.array([10, 20, 30, 40])
mul_array = second_array_from_list * 2

print("Поэлементная сумма:", sum_array)
print("Поэлементное умножение: \n", mul_array)

Поэлементная сумма: [11 22 33 44]
Поэлементное умножение: 
 [[ 2  4  6]
 [ 8 10 12]]


In [8]:
mean_val = range_array.mean()

print("Среднее значение массива range_array:", mean_val)

Среднее значение массива range_array: 4.75
